cache:
  paths:
    - node_modules/

build:
  artifacts:
    paths:
      - build
  image: node:13.11
  script:
    - npm install
    - npm run generate-build-meta
    - npm run build
  stage: build

deploy_dev:
  image: alpine:3.10
  only:
    - dev
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete build/* deploy@$SSH_SERVER_DEV:/var/www/$SITE_DEV/current/public/
  stage: deploy

deploy_prd:
  image: alpine:3.10
  only:
    - master
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -rav --delete build/* deploy@$SSH_SERVER_PRD:/var/www/$SITE_PRD
  stage: deploy