version: "3.8"

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy

services:
  app:
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.${SERVICE_NAME}-prd.rule=Host(`${URL_PRD}`)"
        - "traefik.http.routers.${SERVICE_NAME}-prd.tls.certresolver=le"
        - "traefik.http.services.${SERVICE_NAME}-prd.loadbalancer.server.port=8080"
    image: ${CI_REGISTRY_IMAGE}:${CI_COMMIT_SHORT_SHA}
    networks:
        - reverse-proxy
