export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const FETCH_AGE_GROUPS_CHART_START = 'FETCH_AGE_GROUPS_CHART_START';
export const FETCH_AGE_GROUPS_CHART_SUCCESS = 'FETCH_AGE_GROUPS_CHART_SUCCESS';
export const FETCH_AGE_GROUPS_CHART_FAIL = 'FETCH_AGE_GROUPS_CHART_FAIL';

export const FETCH_SATISFACTIONS_CHART_START = 'FETCH_SATISFACTIONS_CHART_START';
export const FETCH_SATISFACTIONS_CHART_SUCCESS = 'FETCH_SATISFACTIONS_CHART_SUCCESS';
export const FETCH_SATISFACTIONS_CHART_FAIL = 'FETCH_SATISFACTIONS_CHART_FAIL';

export const FETCH_DAILY_VISITORS_CHART_START = 'FETCH_DAILY_VISITORS_CHART_START';
export const FETCH_DAILY_VISITORS_CHART_SUCCESS = 'FETCH_DAILY_VISITORS_CHART_SUCCESS';
export const FETCH_DAILY_VISITORS_CHART_FAIL = 'FETCH_DAILY_VISITORS_CHART_FAIL';